language: go

go:
  - 1.12.x

before_install:
  - mkdir -p $GOPATH/src/k8s.io
  - git clone --branch $TRAVIS_BRANCH https://github.com/kubernetes/kubernetes.git $GOPATH/src/k8s.io/kubernetes
  - wget https://github.com/kubernetes-sigs/kind/releases/download/v0.3.0/kind-linux-amd64
  - chmod +x kind-linux-amd64
  - mv kind-linux-amd64 /tmp/kind

script:
  - /tmp/kind build node-image
  - docker tag kindest/node:latest stevesloka/node:$TRAVIS_BRANCH
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push stevesloka/node:$TRAVIS_BRANCH
